typography_spectrum: 0.0551252334844321
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1771740939002484
  lightness: 0.4391193250194192
  saturation: 0.04222774691879749
  rhythmicContrast: 0.6280444383155555
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23461543885059655
analytics:
  google: null
  facebook: null
  twitter: null
name: Dagligt Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Capturing the little, random moments in the most natural way'
description: Photography with love
purpose: []
